### PR TITLE
Improve getPermissions request and prevent app from crashing when per…

### PR DESCRIPTION
**Pull request by vkyeswa**
- Prevent app from crashing on Android when permission is denied
- Replaced deprecated methods

### CODE REVIEW

**Comment by Idrimi** [comment]
Nice. Thx for the pr. Looks good. Will check & test next week.

**Comment by rennerwins** [comment]
Hi @Idrimi! Any plan on merging this PR?

**Comment by taurix** [comment]
@Idrimi curious if this will be merged?

**Comment by tafelnl** [comment]
A new major of this plugin just got released as a beta version. The plugin is refactored quite a bit. Among others, the API and TypeScript definitions got improved.

It also ships with improved checking and requesting of permissions: it now follows the new standards defined by the Capacitor team.

Check out the newly added docs here: https://capacitor-community.github.io/contacts

Mind you that the new version (v3 and v4) are currently still in beta. However, the beta is tested quite extensively and fairly stable. If you're willing to test it out in your project, it would be much appreciated!

**Pull request closed without merging**
