### PR TITLE
feat(): support v4

### PR DESCRIPTION
**Pull request by rdlabo**
By using `next` tag, This plugin can try to test on Capacitor 4.

```
% npm install @capacitor-community/contacts@next
```

https://github.com/capacitor-community/contacts/releases/tag/v2.0.0-0

However, this update was done automatically by `@rdlabo/capacitor-plugin-to-v4 ` ,and has not been confirmed to work.

https://github.com/rdlabo-team/capacitor-plugin-to-v4

If you have any problems using it, please comment on this thread.

@maintainer Released with next tag to make the world compatible with Capacitor v4. Please check out this pull request and decide if you want to merge or not. Thanks for all your great work, and we look forward to working with you in the future.

### CODE REVIEW

**Comment by RRGT19** [comment]
Any update on this? This fix the issue https://github.com/capacitor-community/contacts/issues/77

**Comment by shodushi** [comment]
> 

for me this temporary fix is working

**Comment by RRGT19** [comment]
@Idrimi 
Help with this, would be awesome to boost this release.

**Comment by CodingCarlos** [comment]
This v2 it's working for me too.

Any idea on how long would it take to merge it?
I have plenty of outdated capacitor dependecies, since my CI flows crash if I update because of this :see_no_evil: 

Thanks!

**Pull request merged**
